<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-12-06 12:50

$extensionPath = t3lib_extMgm::extPath('dyncss');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_dyncss_configuration_beregistry' => $extensionClassesPath . 'Configuration/BeRegistry.php',
	'tx_dyncss_extmgm_statefield' => $extensionClassesPath . 'ExtMgm/StateField.php',
	'tx_dyncss_hooks_t3libpagerendererrenderpreprocesshook' => $extensionClassesPath . 'Hooks/T3libPageRendererRenderPreProcessHook.php',
	'tx_dyncss_parser_abstractparser' => $extensionClassesPath . 'Parser/AbstractParser.php',
	'tx_dyncss_parser_parserinterface' => $extensionClassesPath . 'Parser/ParserInterface.php',
	'tx_dyncss_tslibfecontentpostprocallhook' => $extensionClassesPath . 'Hooks/TslibFeContentPostProcAllHook.php',
	'tx_dyncss_service_dyncssservice' => $extensionClassesPath . 'Service/DyncssService.php',
);
?>